set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports sound]
set_property DRIVE 12 [get_ports sound]
set_property SLEW SLOW [get_ports sound]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN H14 [get_ports sound]
