set_property IOSTANDARD LVCMOS33 [get_ports Bin]
set_property IOSTANDARD LVCMOS33 [get_ports Bout]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports X]
set_property IOSTANDARD LVCMOS33 [get_ports Y]
set_property DRIVE 12 [get_ports Bout]
set_property DRIVE 12 [get_ports D]
set_property SLEW SLOW [get_ports Bout]
set_property SLEW SLOW [get_ports D]
set_property PACKAGE_PIN V10 [get_ports X]
set_property PACKAGE_PIN U11 [get_ports Y]
set_property PACKAGE_PIN U12 [get_ports Bin]
set_property PACKAGE_PIN V11 [get_ports D]
set_property PACKAGE_PIN V12 [get_ports Bout]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
