set_property IOSTANDARD LVCMOS33 [get_ports {light[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports data_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property DRIVE 12 [get_ports {light[4]}]
set_property DRIVE 12 [get_ports {light[3]}]
set_property DRIVE 12 [get_ports {light[2]}]
set_property DRIVE 12 [get_ports {light[1]}]
set_property DRIVE 12 [get_ports {light[0]}]
set_property SLEW SLOW [get_ports {light[4]}]
set_property SLEW SLOW [get_ports {light[3]}]
set_property SLEW SLOW [get_ports {light[2]}]
set_property SLEW SLOW [get_ports {light[1]}]
set_property SLEW SLOW [get_ports {light[0]}]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property PACKAGE_PIN V11 [get_ports {light[4]}]
set_property PACKAGE_PIN V12 [get_ports {light[3]}]
set_property PACKAGE_PIN V14 [get_ports {light[2]}]
set_property PACKAGE_PIN V15 [get_ports {light[1]}]
set_property PACKAGE_PIN T16 [get_ports {light[0]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN F16 [get_ports data_in]
set_property PACKAGE_PIN J15 [get_ports rst_n]



