set_property IOSTANDARD LVCMOS33 [get_ports blue]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports green]
set_property IOSTANDARD LVCMOS33 [get_ports light]
set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property DRIVE 12 [get_ports light]
set_property SLEW SLOW [get_ports light]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property PACKAGE_PIN G14 [get_ports blue]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN R11 [get_ports green]

set_property PACKAGE_PIN N16 [get_ports red]
set_property PACKAGE_PIN J15 [get_ports rst_n]
