set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports Cin]
set_property IOSTANDARD LVCMOS33 [get_ports Cout]
set_property IOSTANDARD LVCMOS33 [get_ports S]
set_property DRIVE 12 [get_ports Cout]
set_property DRIVE 12 [get_ports S]
set_property SLEW SLOW [get_ports Cout]
set_property SLEW SLOW [get_ports S]
set_property PACKAGE_PIN V10 [get_ports A]
set_property PACKAGE_PIN U11 [get_ports B]
set_property PACKAGE_PIN U12 [get_ports Cin]
set_property PACKAGE_PIN V11 [get_ports Cout]
set_property PACKAGE_PIN V12 [get_ports S]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
